services:
  - type: web
    name: minhphan-laravel-ecommerce
    runtime: docker
    plan: starter
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_TIMEZONE
        value: Asia/Ho_Chi_Minh
      - key: DB_CONNECTION
        value: sqlite
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: TRUST_HOSTS_ENABLED
        value: "false"
